### PR TITLE
chore(npm): Babel-ize and Webpack-ify the lib

### PR DESCRIPTION
**Pull request by dmitrizagidulin**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
The minified webpack'd bundle weighs in at a hefty 605K, on first try. Investigating. (JSONDocument makes up for only about 30K of that.)

**Comment by dmitrizagidulin** [comment]
There is 152K of raw (unminified) source code in `src/`. The other 420K are coming in from (most likely) `base64url` and `text-encoding` deps.  

Btw, are we using `qs` or `pem-jwk` anywhere in the code? (Or can we remove them from the package.json)

**Comment by christiansmith** [comment]
qs and pem-jwk are leftover from pre-webcrypto iterations. they can be removed

**Comment by christiansmith** [comment]
We are using base64url, and I just added text-encoding. Maybe this is why there are alternatives to text-encoding package?

**Comment by christiansmith** [comment]
We can't take out text-encoding yet. Need an alternative first.

**Comment by christiansmith** [comment]
I'll merge this if you replace the deleted line for `text-encoding` dependency in `package.json`. It sucks that it's so enormous, but it should stay there until we find a suitable replacement.

**Comment by dmitrizagidulin** [comment]
I didn't delete it - that's just a git diff artifact. (I added webcrypto below it, so its comma status changed, etc)

**Comment by christiansmith** [comment]
oops. still not used to reading the side by side diffs

**Pull request merged**
